name: Build & Deploy

on:
  push:
    branches: [ "prod" ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app to CapRover
        uses: caprover/deploy-from-github@main
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'